# Generated by Django 3.2.4 on 2021-07-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_ticket_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
